### ISSUE TITLE
python 3 issue

### ISSUE THREAD

**Issue by urigoren** [seomoz/word2gauss#20]
The following import works on python2 on my machine, and does not on python3
```
>>> from word2gauss import GaussianEmbedding, iter_pairs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/urig/Workspaces/mine/word2gauss/word2gauss/__init__.py", line 2, in <module>
    from .embeddings import GaussianEmbedding
ImportError: dlopen(/Users/urig/Workspaces/mine/word2gauss/word2gauss/embeddings.so, 2): Symbol not found: _PyCObject_Type
  Referenced from: /Users/urig/Workspaces/mine/word2gauss/word2gauss/embeddings.so
  Expected in: flat namespace
 in /Users/urig/Workspaces/mine/word2gauss/word2gauss/embeddings.so
```

**Comment by matt-peters** [comment]
word2gauss only supports python 2.7 right now.  There is an open PR that gets most of the way to python 3 #12 that has been abandoned, take a look and it might help.
